<?php
//extensions_OpenPBX.conf

include_once('/apps/OpenPBX/www/includes/variables.php');

// hints for user extensions
function _hints_user($ba) {

	$ret = '';

	$query = $ba->query(
		'SELECT ' .
			's.name AS name,' .
			's.username AS username, ' .
			'e.extension AS extension ' .
		'FROM ' .
			'sip_users AS s,' .
			'sip_extensions AS e ' .
		'WHERE ' .
			's.extension = e.id'
	);

	if ($ba->num_rows($query) > 0) {
		$ret .= '; hints for user extensions' ."\n";
		while ($entry = $ba->fetch_array($query)) {
			$ret .=	'exten => ' . $entry['extension'] . ',hint,SIP/' . (empty($entry['username']) ? $entry['extension'] : $entry['username']) ."\n";
		}
		$ret .= "\n";
	}

	return $ret;
}

// create file extensions_OpenPBX.conf
function create_extensions_OpenPBX ($ba) {

	$fn = BAF_APP_AST_CFG . '/extensions_OpenPBX.conf';

	$cont  = '; Generated by OpenPBX \'create_files_ext.php\'' ."\n";
	$cont .= "\n";
	$cont .= '[openpbx_to-internal]' ."\n";
	$cont .= _hints_user($ba);
	$cont .= "\n";
	
	_create_dirs();
	_save_conf($fn, $cont);
}

?>
