<?php

class MainModule {

	private $_name = 'management_mail';
	private $_title = 'Mail Configuration';

	function getName() {
		return($this->_name);
	}

	function getTitle() {
		return($this->_title);
	}

	private function _execute_save_db() {
		$ba = new beroAri();

		$ba->update("UPDATE mail_settings SET " .
					"smtp_host = '" . $_POST['smtp_host'] . "'," .
					"smtp_port = '" . $_POST['smtp_port'] . "'," .
					"smtp_user = '" . $_POST['smtp_user'] . "'," .
					"smtp_pass = '" . $_POST['smtp_pass'] . "'," .
					"smtp_from = '" . $_POST['smtp_from'] . "' " .
				"WHERE id = 1;");

		$ba->update("UPDATE activate SET option = 1 WHERE id = 'activate' AND option < 1;");
	}

	private function _execute_save_file() {

		$conf_dir = BAF_APP_ETC . '/ssmtp';
		$fn = $conf_dir . '/ssmtp.conf';

		$cont =	"# Generated by OpenPBX\n" .
			"\n" .
			"mailhub=" . $_POST['smtp_host'] .":" . $_POST['smtp_port'] . "\n" .
			"AuthUser=" . $_POST['smtp_user'] . "\n" .
			"AuthPass=" . $_POST['smtp_pass'] . "\n" .
			"FromLineOverride=yes\n";

		if (!file_exists($conf_dir)) {
			mkdir($conf_dir);
			chown($conf_dir, 'admin');
			chgrp($conf_dir, 'admin');
		}

		if (($fp = @fopen($fn, 'w'))) {
			fwrite($fp, $cont);
			fclose($fp);

			chown($fn, 'admin');
			chgrp($fn, 'admin');
		}
	}

	function execute() {

		if (!isset($_GET['execute'])) {
			return('');
		}

		$this->_execute_save_db();
		$this->_execute_save_file();

		return("<script>this.window.location.href='" . BAF_URL_BASE . "/index.php?m=" . $_GET['m'] . "';</script>\n");
	}

	function display() {

		$ba = new beroAri();

		$query = $ba->select("SELECT * FROM mail_settings WHERE id = 1;");
		$entry = $ba->fetch_array($query);
		unset($query);

		$ret =	"<form name=\"mail_server\" action=\"" . BAF_URL_BASE . "/index.php?m=" . $_GET['m'] . "&execute\" method=\"POST\">\n" .
			"\t<table class=\"default\">\n" .
			"\t\t<tr>\n" .
			"\t\t\t<th colspan=\"2\">Mail-Server Settings</td>\n" .
			"\t\t</tr>\n" .
			"\t\t<tr>\n" .
			"\t\t\t<td>SMTP-Host</td>\n" .
			"\t\t\t<td>\n" .
			"\t\t\t\t<input type=\"text\" name=\"smtp_host\" value=\"" . $entry['smtp_host'] . "\" />\n" .
			"\t\t\t</td>\n" .
			"\t\t</tr>\n" .
			"\t\t<tr>\n" .
			"\t\t\t<td>SMTP-Port</td>\n" .
			"\t\t\t<td>\n" .
			"\t\t\t\t<input type=\"text\" name=\"smtp_port\" value=\"" . $entry['smtp_port'] . "\" />\n" .
			"\t\t\t</td>\n" .
			"\t\t</tr>\n" .
			"\t\t<tr>\n" .
			"\t\t\t<td>SMTP-User</td>\n" .
			"\t\t\t<td>\n" .
			"\t\t\t\t<input type=\"text\" name=\"smtp_user\" value=\"" . $entry['smtp_user'] . "\" />\n" .
			"\t\t\t</td>\n" .
			"\t\t</tr>\n" .
			"\t\t<tr>\n" .
			"\t\t\t<td>SMTP-Password</td>\n" .
			"\t\t\t<td>\n" .
			"\t\t\t\t<input type=\"password\" name=\"smtp_pass\" value=\"" . $entry['smtp_pass'] . "\" />\n" .
			"\t\t\t</td>\n" .
			"\t\t</tr>\n" .
			"\t\t<tr>\n" .
			"\t\t\t<td>SMTP-From</td>\n" .
			"\t\t\t<td>\n" .
			"\t\t\t\t<input type=\"text\" name=\"smtp_from\" value=\"" . $entry['smtp_from'] . "\" />\n" .
			"\t\t\t</td>\n" .
			"\t\t</tr>\n" .
			"\t\t<tr>\n" .
			"\t\t<tr>\n" .
			"\t\t\t<td></td>\n" .
			"\t\t\t<td>\n" .
			"\t\t\t\t<input type=\"submit\" name=\"smtp_submit\" value=\"Save\" />\n" .
			"\t\t\t</td>\n" .
			"\t\t</tr>\n" .
			"\t</table>\n" .
			"</form>\n";

		return($ret);
	}
}

?>
